name: Trigger auto deployment for mapbot-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/mapbot-dev-AutoDeployTrigger-de3f59e2-5170-4885-bc00-fcb2c19a88a5.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
          file: ./Dockerfile
          context: .


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MAPBOTDEV_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n mapbot-dev -g ampstatusazfunction --server ghcr.io --username  ${{ secrets.MAPBOTDEV_REGISTRY_USERNAME }} --password ${{ secrets.MAPBOTDEV_REGISTRY_PASSWORD }}
            az containerapp update -n mapbot-dev -g ampstatusazfunction --image ghcr.io/deltxprt/mapbot:${{ github.sha }}
